from typing import Dict, List

from .schema import Permission, PermissionGroup, Role

SCOPES: Dict[str, str] = {
    "platform": "System-wide access across all tenants",
    "organization": "Access scoped to a single organization",
    "marketplace_provider": "Access scoped to the provider account",
    "self": "Access scoped to the authenticated user only",
}

PERMISSIONS: Dict[str, Permission] = {
    "user.read": Permission(
        key="user.read",
        description="View user profiles and status",
        scopes=["platform", "organization", "self"],
    ),
    "user.update": Permission(
        key="user.update",
        description="Update user profiles and status",
        scopes=["platform", "organization", "self"],
    ),
    "user.suspend": Permission(
        key="user.suspend",
        description="Suspend or ban users",
        scopes=["platform", "organization"],
    ),
    "user.verify": Permission(
        key="user.verify",
        description="Verify user identity or documents",
        scopes=["platform", "organization"],
    ),
    "org.read": Permission(
        key="org.read",
        description="View organization accounts",
        scopes=["platform", "organization"],
    ),
    "org.update": Permission(
        key="org.update",
        description="Update organization settings",
        scopes=["platform", "organization"],
    ),
    "org.suspend": Permission(
        key="org.suspend",
        description="Suspend organization accounts",
        scopes=["platform"],
    ),
    "role.create": Permission(
        key="role.create",
        description="Create new roles",
        scopes=["platform"],
    ),
    "role.update": Permission(
        key="role.update",
        description="Update existing roles",
        scopes=["platform"],
    ),
    "role.assign": Permission(
        key="role.assign",
        description="Assign roles to users",
        scopes=["platform", "organization"],
    ),
    "permission.update": Permission(
        key="permission.update",
        description="Update role permissions",
        scopes=["platform"],
    ),
    "opp.create": Permission(
        key="opp.create",
        description="Create opportunities",
        scopes=["platform", "organization"],
    ),
    "opp.read": Permission(
        key="opp.read",
        description="Read opportunities",
        scopes=["platform", "organization", "self"],
    ),
    "opp.update": Permission(
        key="opp.update",
        description="Update opportunities",
        scopes=["platform", "organization"],
    ),
    "opp.publish": Permission(
        key="opp.publish",
        description="Publish opportunities",
        scopes=["platform", "organization"],
    ),
    "opp.unpublish": Permission(
        key="opp.unpublish",
        description="Unpublish opportunities",
        scopes=["platform", "organization"],
    ),
    "opp.delete": Permission(
        key="opp.delete",
        description="Delete opportunities",
        scopes=["platform", "organization"],
    ),
    "opp.moderate": Permission(
        key="opp.moderate",
        description="Approve or reject opportunities",
        scopes=["platform"],
    ),
    "app.read": Permission(
        key="app.read",
        description="Read applications",
        scopes=["platform", "organization", "self"],
    ),
    "app.export": Permission(
        key="app.export",
        description="Export application data",
        scopes=["platform", "organization"],
    ),
    "app.move_stage": Permission(
        key="app.move_stage",
        description="Move applications through pipeline stages",
        scopes=["platform", "organization"],
    ),
    "app.comment": Permission(
        key="app.comment",
        description="Comment on applications",
        scopes=["platform", "organization"],
    ),
    "app.reject": Permission(
        key="app.reject",
        description="Reject applications",
        scopes=["platform", "organization"],
    ),
    "app.accept": Permission(
        key="app.accept",
        description="Accept applications",
        scopes=["platform", "organization"],
    ),
    "service.create": Permission(
        key="service.create",
        description="Create marketplace services",
        scopes=["marketplace_provider"],
    ),
    "service.update": Permission(
        key="service.update",
        description="Update marketplace services",
        scopes=["marketplace_provider"],
    ),
    "service.publish": Permission(
        key="service.publish",
        description="Publish marketplace services",
        scopes=["marketplace_provider"],
    ),
    "provider.approve": Permission(
        key="provider.approve",
        description="Approve marketplace providers",
        scopes=["platform"],
    ),
    "provider.suspend": Permission(
        key="provider.suspend",
        description="Suspend marketplace providers",
        scopes=["platform"],
    ),
    "order.read": Permission(
        key="order.read",
        description="Read marketplace orders",
        scopes=["platform", "marketplace_provider"],
    ),
    "order.refund": Permission(
        key="order.refund",
        description="Refund marketplace orders",
        scopes=["platform"],
    ),
    "payout.manage": Permission(
        key="payout.manage",
        description="Manage provider payouts",
        scopes=["platform", "marketplace_provider"],
    ),
    "program.create": Permission(
        key="program.create",
        description="Create training programs",
        scopes=["platform", "organization"],
    ),
    "cohort.manage": Permission(
        key="cohort.manage",
        description="Manage program cohorts",
        scopes=["platform", "organization"],
    ),
    "enrollment.manage": Permission(
        key="enrollment.manage",
        description="Manage enrollments",
        scopes=["platform", "organization"],
    ),
    "attendance.manage": Permission(
        key="attendance.manage",
        description="Manage attendance",
        scopes=["platform", "organization"],
    ),
    "certificate.issue": Permission(
        key="certificate.issue",
        description="Issue completion certificates",
        scopes=["platform", "organization"],
    ),
    "plan.manage": Permission(
        key="plan.manage",
        description="Manage billing plans",
        scopes=["platform"],
    ),
    "subscription.manage": Permission(
        key="subscription.manage",
        description="Manage subscriptions",
        scopes=["platform", "organization"],
    ),
    "invoice.read": Permission(
        key="invoice.read",
        description="Read invoices",
        scopes=["platform", "organization", "self"],
    ),
    "refund.manage": Permission(
        key="refund.manage",
        description="Manage refunds",
        scopes=["platform"],
    ),
    "coupon.manage": Permission(
        key="coupon.manage",
        description="Manage coupons",
        scopes=["platform"],
    ),
    "blog.manage": Permission(
        key="blog.manage",
        description="Manage blog content",
        scopes=["platform"],
    ),
    "faq.manage": Permission(
        key="faq.manage",
        description="Manage FAQ content",
        scopes=["platform"],
    ),
    "pages.manage": Permission(
        key="pages.manage",
        description="Manage static pages",
        scopes=["platform"],
    ),
    "ticket.manage": Permission(
        key="ticket.manage",
        description="Manage support tickets",
        scopes=["platform", "organization"],
    ),
    "ticket.assign": Permission(
        key="ticket.assign",
        description="Assign support tickets",
        scopes=["platform"],
    ),
    "ticket.close": Permission(
        key="ticket.close",
        description="Close support tickets",
        scopes=["platform", "organization"],
    ),
    "audit.read": Permission(
        key="audit.read",
        description="Read audit logs",
        scopes=["platform"],
    ),
    "audit.export": Permission(
        key="audit.export",
        description="Export audit logs",
        scopes=["platform"],
    ),
    "report.read": Permission(
        key="report.read",
        description="Read reports and analytics",
        scopes=["platform", "organization"],
    ),
    "report.export": Permission(
        key="report.export",
        description="Export reports and analytics",
        scopes=["platform", "organization"],
    ),
    "settings.manage": Permission(
        key="settings.manage",
        description="Manage system settings",
        scopes=["platform"],
    ),
    "settings.notifications": Permission(
        key="settings.notifications",
        description="Manage notification settings",
        scopes=["platform"],
    ),
    "settings.seo": Permission(
        key="settings.seo",
        description="Manage SEO settings",
        scopes=["platform"],
    ),
    "settings.payments": Permission(
        key="settings.payments",
        description="Manage payment gateways",
        scopes=["platform"],
    ),
    "settings.language": Permission(
        key="settings.language",
        description="Manage languages",
        scopes=["platform"],
    ),
    "settings.extensions": Permission(
        key="settings.extensions",
        description="Manage extensions",
        scopes=["platform"],
    ),
    "settings.maintenance": Permission(
        key="settings.maintenance",
        description="Manage maintenance mode",
        scopes=["platform"],
    ),
    "settings.gdpr": Permission(
        key="settings.gdpr",
        description="Manage GDPR and cookie settings",
        scopes=["platform"],
    ),
    "settings.sitemap": Permission(
        key="settings.sitemap",
        description="Manage sitemap",
        scopes=["platform"],
    ),
    "settings.robots": Permission(
        key="settings.robots",
        description="Manage robots.txt",
        scopes=["platform"],
    ),
    "settings.custom_css": Permission(
        key="settings.custom_css",
        description="Manage custom CSS",
        scopes=["platform"],
    ),
    "settings.frontend": Permission(
        key="settings.frontend",
        description="Manage frontend content",
        scopes=["platform"],
    ),
    "profile.update": Permission(
        key="profile.update",
        description="Update own profile",
        scopes=["self"],
    ),
    "app.submit": Permission(
        key="app.submit",
        description="Submit applications",
        scopes=["self"],
    ),
}

PERMISSION_GROUPS: Dict[str, PermissionGroup] = {
    "users": PermissionGroup(
        key="users",
        label="Users",
        permissions=["user.read", "user.update", "user.suspend", "user.verify"],
    ),
    "organizations": PermissionGroup(
        key="organizations",
        label="Organizations",
        permissions=["org.read", "org.update", "org.suspend"],
    ),
    "roles": PermissionGroup(
        key="roles",
        label="Roles",
        permissions=["role.create", "role.update", "role.assign", "permission.update"],
    ),
    "opportunities": PermissionGroup(
        key="opportunities",
        label="Opportunities",
        permissions=[
            "opp.read",
            "opp.create",
            "opp.update",
            "opp.publish",
            "opp.unpublish",
            "opp.delete",
            "opp.moderate",
        ],
    ),
    "applications": PermissionGroup(
        key="applications",
        label="Applications",
        permissions=[
            "app.read",
            "app.export",
            "app.move_stage",
            "app.comment",
            "app.reject",
            "app.accept",
            "app.submit",
        ],
    ),
    "marketplace": PermissionGroup(
        key="marketplace",
        label="Marketplace",
        permissions=[
            "service.create",
            "service.update",
            "service.publish",
            "provider.approve",
            "provider.suspend",
            "order.read",
            "order.refund",
            "payout.manage",
        ],
    ),
    "programs": PermissionGroup(
        key="programs",
        label="Programs",
        permissions=[
            "program.create",
            "cohort.manage",
            "enrollment.manage",
            "attendance.manage",
            "certificate.issue",
        ],
    ),
    "billing": PermissionGroup(
        key="billing",
        label="Billing",
        permissions=[
            "plan.manage",
            "subscription.manage",
            "invoice.read",
            "refund.manage",
            "coupon.manage",
        ],
    ),
    "content": PermissionGroup(
        key="content",
        label="Content",
        permissions=["blog.manage", "faq.manage", "pages.manage"],
    ),
    "support": PermissionGroup(
        key="support",
        label="Support",
        permissions=["ticket.manage", "ticket.assign", "ticket.close"],
    ),
    "audit": PermissionGroup(
        key="audit",
        label="Audit",
        permissions=["audit.read", "audit.export"],
    ),
    "reports": PermissionGroup(
        key="reports",
        label="Reports",
        permissions=["report.read", "report.export"],
    ),
    "settings": PermissionGroup(
        key="settings",
        label="Settings",
        permissions=[
            "settings.manage",
            "settings.notifications",
            "settings.seo",
            "settings.payments",
            "settings.language",
            "settings.extensions",
            "settings.maintenance",
            "settings.gdpr",
            "settings.sitemap",
            "settings.robots",
            "settings.custom_css",
            "settings.frontend",
        ],
    ),
    "profile": PermissionGroup(
        key="profile",
        label="Profile",
        permissions=["profile.update"],
    ),
}

ROLE_DEFINITIONS: Dict[str, Role] = {
    "admin_owner": Role(
        key="admin_owner",
        label="Admin Owner",
        description="Full system control with editable roles and permissions",
        default_scopes=["platform"],
        permissions=["*"],
    ),
    "super_admin": Role(
        key="super_admin",
        label="Super Admin",
        description="Full platform operations except owner-only controls",
        default_scopes=["platform"],
        permissions=[
            "user.read",
            "user.update",
            "user.suspend",
            "user.verify",
            "org.read",
            "org.update",
            "role.assign",
            "opp.create",
            "opp.update",
            "opp.publish",
            "opp.unpublish",
            "opp.delete",
            "opp.moderate",
            "app.read",
            "app.export",
            "app.move_stage",
            "app.comment",
            "app.reject",
            "app.accept",
            "service.create",
            "service.update",
            "service.publish",
            "provider.approve",
            "provider.suspend",
            "order.read",
            "order.refund",
            "payout.manage",
            "program.create",
            "cohort.manage",
            "enrollment.manage",
            "attendance.manage",
            "certificate.issue",
            "plan.manage",
            "subscription.manage",
            "invoice.read",
            "refund.manage",
            "coupon.manage",
            "blog.manage",
            "faq.manage",
            "pages.manage",
            "ticket.manage",
            "ticket.assign",
            "ticket.close",
            "audit.read",
            "settings.manage",
            "settings.notifications",
            "settings.seo",
            "settings.payments",
            "settings.language",
            "settings.extensions",
            "settings.maintenance",
            "settings.gdpr",
            "settings.sitemap",
            "settings.robots",
            "settings.custom_css",
            "settings.frontend",
        ],
    ),
    "moderator": Role(
        key="moderator",
        label="Moderator",
        description="Moderates content and reported activity",
        default_scopes=["platform"],
        permissions=[
            "opp.moderate",
            "app.read",
            "app.comment",
            "user.read",
            "ticket.manage",
            "report.read",
        ],
    ),
    "publisher": Role(
        key="publisher",
        label="Publisher",
        description="Manages platform content",
        default_scopes=["platform"],
        permissions=["blog.manage", "faq.manage", "pages.manage"],
    ),
    "finance_admin": Role(
        key="finance_admin",
        label="Finance Admin",
        description="Manages billing, invoices, and refunds",
        default_scopes=["platform"],
        permissions=[
            "plan.manage",
            "subscription.manage",
            "invoice.read",
            "refund.manage",
            "coupon.manage",
            "order.read",
            "order.refund",
            "payout.manage",
        ],
    ),
    "support_agent": Role(
        key="support_agent",
        label="Support Agent",
        description="Handles support tickets and user inquiries",
        default_scopes=["platform"],
        permissions=["ticket.manage", "ticket.assign", "ticket.close", "user.read"],
    ),
    "marketplace_provider": Role(
        key="marketplace_provider",
        label="Marketplace Provider",
        description="Publishes marketplace services and manages orders",
        default_scopes=["marketplace_provider", "self"],
        permissions=[
            "service.create",
            "service.update",
            "service.publish",
            "order.read",
            "payout.manage",
            "profile.update",
        ],
    ),
    "organization_owner": Role(
        key="organization_owner",
        label="Organization Owner",
        description="Owns organization and manages hiring operations",
        default_scopes=["organization"],
        permissions=[
            "org.read",
            "org.update",
            "role.assign",
            "opp.create",
            "opp.update",
            "opp.publish",
            "opp.unpublish",
            "opp.delete",
            "app.read",
            "app.move_stage",
            "app.comment",
            "app.reject",
            "app.accept",
            "subscription.manage",
            "invoice.read",
        ],
    ),
    "hr_manager": Role(
        key="hr_manager",
        label="HR Manager",
        description="Manages applicants and hiring pipelines",
        default_scopes=["organization"],
        permissions=[
            "opp.create",
            "opp.update",
            "opp.publish",
            "app.read",
            "app.move_stage",
            "app.comment",
            "app.reject",
            "app.accept",
        ],
    ),
    "recruiter": Role(
        key="recruiter",
        label="Recruiter",
        description="Sources candidates and manages applications",
        default_scopes=["organization"],
        permissions=["opp.read", "app.read", "app.move_stage", "app.comment"],
    ),
    "interviewer": Role(
        key="interviewer",
        label="Interviewer",
        description="Evaluates candidates during interviews",
        default_scopes=["organization"],
        permissions=["app.read", "app.comment"],
    ),
    "opportunity_manager": Role(
        key="opportunity_manager",
        label="Opportunity Manager",
        description="Manages volunteer, scholarship, and program opportunities",
        default_scopes=["organization"],
        permissions=["opp.create", "opp.update", "opp.publish", "opp.unpublish"],
    ),
    "job_seeker": Role(
        key="job_seeker",
        label="Job Seeker",
        description="Finds and applies to opportunities",
        default_scopes=["self"],
        permissions=["profile.update", "app.submit", "app.read"],
    ),
    "volunteer_applicant": Role(
        key="volunteer_applicant",
        label="Volunteer/Scholarship Applicant",
        description="Applies to volunteer and scholarship opportunities",
        default_scopes=["self"],
        permissions=["profile.update", "app.submit", "app.read"],
    ),
}
